server:
  port: 2001

spring:
  application:
    name: seata-order-service
  cloud:
    alibaba:
      seata:
        tx-service-group: default-tx-group
    nacos:
      discovery:
        server-addr: localhost:8848
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seata_order
    username: root
    password: ca123456

#seata:
#  registry:
#    type: nacos
#    nacos:
#      server-addr: 127.0.0.1:8848
#      namespace:
#      group: DEFAULT
#      application: seata-server
#      username: nacos
#      password: nacos
#  tx-service-group: seata-demo
#  service:
#    vgroup-mapping:
#      seata-demo: DEFAULT


# seata配置
seata:
  enabled: true
#  application-id: seata-order-service
  # Seata 事务组编号，此处需于 seata 相同
  tx-service-group: default-tx-group
  config:
    type: nacos
    nacos:
      # nacos ip地址
      server-addr: 127.0.0.1:8848
      group: DEFAULT_GROUP
      namespace:
      username:
      password:
      data-id: seataServer.properties # 读取 nacos seata 配置
  registry:
    type: nacos
    nacos:
#      application: seata-server # seata 服务名
      # nacos ip地址
      server-addr: 127.0.0.1:8848
      group: DEFAULT_GROUP
  service:
    # 事务组对应的集群民称
    vgroup-mapping.default-tx-group: DEFAULT
    # seata-server的地址
    grouplist.seata-server: 127.0.0.1:7091

feign:
  hystrix:
    enabled: false

logging:
  level:
    io:
      seata: info

mybatis:
  mapperLocations: classpath:mapper/*.xml